os:
    - linux
language: c
install:
    - git clone -b devel git://github.com/Araq/Nim.git
    - (cd Nim && sh build.sh)
    - export PATH=`pwd`/Nim/bin:$PATH
    - git clone https://github.com/nim-lang/nimble.git
    - (cd nimble && nim c src/nimble)
    - export PATH=`pwd`/nimble/src:$PATH
    - nimble install --accept
script: make
